### PR TITLE
Split package and add extras

### LINKED ISSUE #40: How do I install extras?
At the moment it is unclear to me how I would for example do the equivalent of `pip install apache-beam[gcp]` using this feedstock, is this possible?

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #40

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
```
   Encountered problems while solving:
     - nothing provides facets-overview >=1.0.0,<2 needed by apache-beam-with-interactive-2.32.0-py38h578d9bd_1
     - nothing provides requested facets-overview >=1.0.0,<2
     - nothing provides requested jupyter-client >=6.1.11,<6.1.13
     - nothing provides requested timeloop >=1.0.2,<2
```
Looks like the `interactive` extra won't be easy to add yet.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@aaltay and @sodre, I'm reasonably confident that this will build okay based on my local tests.  Do you want to review?  The approach is similar to [airflow](https://github.com/conda-forge/airflow-feedstock/blob/master/recipe/meta.yaml), as @sodre already knows.

As you will have seen, I wasn't able to get the `interactive` extra working.  `timeloop` would be very easy to add but [facets_overview](https://github.com/PAIR-code/facets/tree/1.0.0/facets_overview) doesn't appear to be a standard python package and `grayskull` isn't able to make a conda recipe from the pypi recipe.  So I will let that one be.

**Comment by aaltay** [comment]
I am not very familiar with conda env, but would it make sense to create a new package instead of breaking this? (Would not this prevent existing users from upgrading?)

**Comment by xylar** [comment]
@aaltay,
> would it make sense to create a new package instead of breaking this?

This is a common practice for handling the equivalent of extras on pypi.  While you could create separate feedstocks for each of the packages with extras, that would be very tedious because each feedstock would need to be updated when there is a new release of  `apache-beam`.  It's much easier to have the main package and each of the packages with extras get updated at once.

> (Would not this prevent existing users from upgrading?)

No, there should be no problem with upgrading.  If a user currently has just the `apache-beam` package installed, they can upgrade as normal.  If they install one of the `apache-beam-with-*` packages instead, they will be able to update that and the `apache-beam` package that is a dependency together whenever there is an update.

**Comment by xylar** [comment]
@aaltay, you do seem to be right that upgrading can be a little tricky.  I'm testing out using `airflow`, which uses the same approach.  I tried:
```
conda create -y test python=3.8 airflow-with-apache-atlas=2.1.0
conda activate test
conda upgrade airflow-with-apache-atlas
```
but conda didn't upgrade airflow or airflow-with-apache-atlas.  Nor did this:
```
conda deactivate
conda create -y test python=3.8 airflow-with-apache-atlas=2.1.0
conda activate test
conda upgrade --all
```

This worked:
```
conda deactivate
conda create -y test python=3.8 airflow-with-apache-atlas=2.1.0
conda activate test
conda install airflow-with-apache-atlas=2.1.4
```
as did this:
```
conda create -y test python=3.8 airflow-with-apache-atlas=2.1.0
conda activate test
conda install airflow=2.1.4
```
I don't think any of this has to do with the packages with extras, though.  I'm seeing the same reluctance to upgrade without an explicit request to install a later version when I just try `airflow` on its own (without the `-with-apache-atlas` extra).  So I think it's more of a conda thing than anything with this packaging approach.

I hope that helps some.

**Comment by xylar** [comment]
@aaltay, do you still have concerns?

@sodre, I'm not sure if you're still maintaining conda packages but let me know if you have thoughts or changes you'd like to see.

**Comment by aaltay** [comment]
Thank you @xylar, this addresses my concerns. I did not know much about the split packages but read about it and this change looks good to me.

If you feel like it, I think a simple addition to the readme about what extras are available would be useful, but this is not a blocker.

**Comment by xylar** [comment]
Thanks!

> If you feel like it, I think a simple addition to the readme about what extras are available would be useful, but this is not a blocker.

Unfortunately, we can't customize the README. Any changes we make will be lost during the next rerender of the feedstock.

**Pull request merged**
