### PR TITLE
Pubsub dependency

### PR DESCRIPTION
**Pull request by casperlchristensen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Apache-Beam 2.41.0 needs [updated versions](https://github.com/apache/beam/blob/v2.41.0/sdks/python/setup.py#L278) of PubSub and PubSubLite. Beam 2.41.0 will try to serialise the PubSub message using [a new method ](https://github.com/apache/beam/blob/v2.41.0/sdks/python/apache_beam/io/gcp/pubsub.py#L181)which, compared to [the old method](https://github.com/apache/beam/blob/v2.34.0/sdks/python/apache_beam/io/gcp/pubsub.py#L153), will throw an AttributeError.

### CODE REVIEW

**Comment by casperlchristensen** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@casperlchristensen, I'm really sorry I missed this in #53.  I try to be careful but some dependency changes sometimes slip by, particularly for the extras.

It looks like `google-cloud-pubsublite` isn't on conda-forge yet so I'll make a recipe for it ASAP.

**Comment by aaltay** [comment]
@xylar - thank you very much once again!
@dpcollins-google - FYI.

**Comment by xylar** [comment]
https://github.com/conda-forge/staged-recipes/pull/20353

**Comment by xylar** [comment]
Once this goes in, I can also patch repo data to fix the problems with build 0.

**Comment by xylar** [comment]
> Once this goes in, I can also patch repo data to fix the problems with build 0.

I think I'm going to skip that and hope the new build gets pulled in.  @casperlchristensen, please let me know (after a few hours so the package is available) whether you're now getting build 1 or if you're still stuck with build 0.  If the latter, I'll patch it.

**Pull request merged**
