### PR TITLE
Add xylar as a maintainer

### PR DESCRIPTION
**Pull request by xylar**
No bumping the build number because we don't need a new package for this.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I have built mock 2.0.0 for python 3.8 and 3.9 to try to get the backlog of updates in.  I would be happy to merge the remaining 4 open PRs (from oldest to newest) if you add me as a maintianer.

**Comment by xylar** [comment]
@conda-forge/apache-beam, this is ready for review.  No need to worry about the failed python 3.8 builds.  I will get python 3.8 working in #25.  I have a local build that is working.

**Comment by aaltay** [comment]
Hi @xylar, welcome to the project and thanks a lot for helping here. We did not make much progress on py 3.8 and 3.9 for a while!

**Pull request merged**
