### PR TITLE
Enable Python3.10 builds

### PR DESCRIPTION
**Pull request by andersy005**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by andersy005** [comment]
@conda-forge-admin, please rerender

**Comment by andersy005** [comment]
The Python 3.10 builds are failing due to missing packages for `pymongo`.  It appears the earliest version of `pymongo` built for Python3.10 is `v4.0.1`


```bash
The reported errors are:
- Encountered problems while solving:
-   - package apache-beam-2.42.0-py310h5764c6d_0 requires pymongo >=3.8.0,<4.0.0, but none of the providers can be installed

```

However, apache-beams still requires versions earlier than `v4.0.0`: https://github.com/apache/beam/blob/77116c5c81459c43f4f3dfa4caa7f0e417d91fef/sdks/python/setup.py#L254

**Comment by xylar** [comment]
The repo also doesn't claim that apache-beam itself is python 3.10 compatible:
https://github.com/apache/beam/blob/v2.42.0/sdks/python/setup.py#L335-L338

**Comment by xylar** [comment]
That should change in the next release, base on `master`:
https://github.com/apache/beam/blob/master/sdks/python/setup.py#L365-L368

**Comment by xylar** [comment]
The pymongo issue seems easy to solve, see: https://github.com/conda-forge/pymongo-feedstock/pull/74#issuecomment-1303100481

**Comment by xylar** [comment]
The pymongo issue should be fixed in https://github.com/conda-forge/pymongo-feedstock/pull/75.

But I still hesitate to enable python 3.10 support for this release.  I think we need to wait for the next one.  We can at least re-test once the packages from https://github.com/conda-forge/pymongo-feedstock/pull/75 get built.

**Comment by xylar** [comment]
@andersy005, sorry that my responses have not been more supportive.  I really appreciate you getting the ball rolling on this.  Even if we aren't able to enable python 3.10 right away, we'll be more ready for it when apache-beam 2.43.0 gets released.

**Comment by andersy005** [comment]
> The repo also doesn't claim that apache-beam itself is python 3.10 compatible: [https://github.com/apache/beam/blob/v2.42.0/sdks/python/setup.py#L335-L338](https://github.com/apache/beam/blob/v2.42.0/sdks/python/setup.py?rgh-link-date=2022-11-04T08%3A07%3A46Z#L335-L338)

I was able to install `apache-beam` via `pip` in an environment with Python3.10, and this is what got me thinking we could build it for conda-forge as well. 

```python

In [1]: import apache_beam
/home/andersy005/mambaforge/envs/test/lib/python3.10/site-packages/apache_beam/__init__.py:79: UserWarning: This version of Apache Beam has not been sufficiently tested on Python 3.10. You may encounter bugs or missing features.
  warnings.warn(

In [2]: import sys

In [3]: sys.version_info
Out[3]: sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)

In [4]: apache_beam.__version__
Out[4]: '2.42.0'
```



> @andersy005, sorry that my responses have not been more supportive. I really appreciate you getting the ball rolling on this. Even if we aren't able to enable python 3.10 right away, we'll be more ready for it when apache-beam 2.43.0 gets released.

@xylar, no worries :) I appreciate you taking the time to look into this. i'll keep an eye out for the next release

**Comment by xylar** [comment]
@andersy005, that's interesting!  I don't know how strictly pip enforces python version specified by the packages.  I can also check if the pypi package has different python version restrictions than the GitHub repo suggests.

**Comment by xylar** [comment]
If you look here, they haven't built any wheels for python 3.10 so I wonder why it even works.
https://pypi.org/project/apache-beam/#files

**Comment by xylar** [comment]
@andersy005, python 3.10 should be enabled in #59 once that can be built (we're waiting on a dependency).

**Comment by andersy005** [comment]
thank you for the heads up, @xylar! i'm going to keep an eye out for #59

**Pull request closed without merging**
