### PR TITLE
try removing py3.9 limitation

### PR DESCRIPTION
**Pull request by rabernat**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Thanks so much for maintaining this recipe! 🙏 

I see that this recipe doesn't support python 3.9

https://github.com/conda-forge/apache-beam-feedstock/blob/5f83ff56c20956e74940e871878e9fb60fe96e30/recipe/meta.yaml#L14-L15

However, Beam support for python 3.9 overall seems solid now (see  https://issues.apache.org/jira/browse/BEAM-12000?focusedCommentId=17541173&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17541173). Therefore, I am naively trying to remove the python 3.9 limitation to see if we can get this build working for 3.9.

Thanks for your patience. I'm new to Beam.

### CODE REVIEW

**Comment by rabernat** [comment]
Ok, that didn't have the intended effect. I guess I don't understand where this recipe is specifying not to build for python 3.9.  😕

**Comment by xylar** [comment]
@rabernat, thankd for trying this.  I'll fix it.

**Comment by xylar** [comment]
> Ok, that didn't have the intended effect. I guess I don't understand where this recipe is specifying not to build for python 3.9.

@rabernat, you have to rerender (as in the instructions above) in order for your changes to take effect.  But by removing the skip entirely, you would have added windows and python 3.10 builds, neither of which will work.  So the right thing to try is to bump up the skip to `py >=310`, as I have done.

We will see if the dependencies that gave us trouble before have loosened restrictions.  Previously, there weren't python 3.9 builds on conda-forge of dependencies with the restrictions that Apache-Beam uses.  It would likely be possible to go to their respective feedstocks and build new packages (including python 3.9) of those older packages.  But often as a maintianer it's a rabbit hole that isn't worth the time unless you know it's needed.

**Comment by xylar** [comment]
Looks like we're in business!

**Comment by xylar** [comment]
@rabernat, give it an hour or so and the python 3.9 packages should be there.

**Comment by rabernat** [comment]
Xylar thank you so much for your help here! 

It's great to run into an old friend on GitHub. Hope to reconnect some time in the near future. I just stalked you GitHub profile and it looks like you've been doing lots of cool data orchestration stuff! 🤓  I'd love to explain what we are up to with Pangeo Forge. If you're curious what we are using Beam for, the answer is here: https://github.com/pangeo-forge/pangeo-forge-recipes/issues/256

**Comment by xylar** [comment]
Yeah, I just heard about this last week when @jbusecke gave a great seminar for our group at LANL!  I didn't know that Apache Beam was part of the architecture, though.  That's quite interesting.

I'm thinking of joining the pangeo biweekly meetings if that would be welcome.  It would be fun to work toward more support for unstructured meshes.

**Comment by aaltay** [comment]
Thank you @xylar for keeping this updated. And hi @rabernat. I was not aware of pangeo-forge considering Beam. Happy to see that. And feel free to reach out if you think that we can help.

It would be amazing to see geoscience related talks at Beam summit or other Beam events, if your community would be interested in that :)

**Pull request merged**
